const AG_DOCS = {
  html: 'https://developer.mozilla.org/ko/docs/Web/HTML',
  css: 'https://developer.mozilla.org/ko/docs/Web/CSS',
  js: 'https://developer.mozilla.org/ko/docs/Web/JavaScript',
  react: 'https://ko.react.dev/learn',
  git: 'https://git-scm.com/doc',
  github: 'https://docs.github.com/ko/pages'
};

const AG_CATEGORIES = {
  html: 'HTML',
  css: 'CSS',
  javascript: 'JavaScript',
  react: 'React',
  git: 'Git/GitHub',
  web: '웹 기초'
};

const AG_POSTS = [
  {seq:1, slug:'html-basic-structure', category:'html', publishAt:'2026-06-22T13:00:00+09:00', title:'HTML 기본 구조 쉽게 이해하기', type:'개념 설명형', doc:'html', related:[2,6], problem:'HTML 파일을 처음 만들었는데 doctype, head, body가 각각 무슨 역할인지 헷갈리는 상황', summary:'HTML 문서는 화면에 보이는 내용과 브라우저가 참고하는 정보를 나누어 작성합니다. 처음에는 외울 것보다 큰 틀을 이해하는 것이 중요합니다.', codeTitle:'기본 HTML 문서', code:'<!doctype html>\n<html lang="ko">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>첫 HTML 문서</title>\n</head>\n<body>\n  <h1>안녕하세요</h1>\n  <p>처음 만든 웹페이지입니다.</p>\n</body>\n</html>', details:['doctype은 브라우저에게 이 문서가 최신 HTML 방식으로 작성되었다고 알려주는 신호입니다. 화면에 직접 보이지는 않지만 문서의 출발점 역할을 합니다.','head 영역에는 제목, 문자 인코딩, 모바일 화면 설정처럼 브라우저와 검색엔진이 참고하는 정보가 들어갑니다. 사용자에게 보이는 본문은 body 안에 작성합니다.','초보 단계에서는 태그를 많이 아는 것보다 문서 구조를 안정적으로 만드는 습관이 더 중요합니다. 구조가 흔들리면 CSS나 JavaScript를 붙일 때도 원인을 찾기 어려워집니다.'], checklist:['doctype을 문서 맨 위에 작성했는지 확인하기','html 태그에 lang="ko"를 넣었는지 확인하기','meta charset과 viewport가 head 안에 있는지 확인하기','화면에 보이는 내용은 body 안에 작성하기']},
  {seq:2, slug:'css-class-id-difference', category:'css', publishAt:'2026-06-22T17:00:00+09:00', title:'class와 id 차이 쉽게 정리', type:'차이 비교형', doc:'css', related:[1,8], problem:'CSS를 적용할 때 class와 id를 아무렇게나 쓰면서 나중에 스타일 충돌이 생기는 상황', summary:'class는 여러 요소에 반복해서 쓰기 좋고, id는 한 페이지에서 특정 요소 하나를 구분할 때 사용합니다.', codeTitle:'버튼 3개 스타일링', code:'<button class="btn primary">저장</button>\n<button class="btn">취소</button>\n<button id="deleteButton" class="btn danger">삭제</button>\n\n<style>\n.btn { padding: 10px 14px; border: 1px solid #ddd; }\n.primary { background: #2563eb; color: white; }\n#deleteButton { border-color: #ef4444; }\n</style>', details:['class는 같은 디자인 규칙을 여러 곳에 재사용할 때 편합니다. 버튼, 카드, 입력창처럼 반복되는 UI에는 class가 자연스럽습니다.','id는 페이지 안에서 고유해야 하므로 스타일링보다 JavaScript에서 특정 요소를 정확히 찾을 때 더 자주 쓰입니다.','CSS 선택자 우선순위에서는 id가 class보다 강합니다. 그래서 id를 남발하면 나중에 스타일을 덮어쓰기 어려워질 수 있습니다.'], compare:[['구분','class','id'],['사용 횟수','여러 요소에 반복 가능','한 페이지에서 하나 권장'],['주 용도','공통 스타일','고유 요소 식별'],['CSS 우선순위','보통','강함']], checklist:['반복되는 디자인은 class로 만들기','id는 꼭 하나만 필요한 요소에 쓰기','스타일이 안 바뀔 때 id 우선순위 때문인지 확인하기','JavaScript 선택 목적과 CSS 스타일 목적을 구분하기']},
  {seq:3, slug:'js-var-let-const', category:'javascript', publishAt:'2026-06-22T21:00:00+09:00', title:'var, let, const 차이 쉽게 정리', type:'차이 비교형', doc:'js', related:[8,21], problem:'변수를 만들 때 var, let, const 중 무엇을 써야 하는지 헷갈리는 상황', summary:'현대 JavaScript에서는 기본적으로 const를 쓰고, 값이 바뀌어야 할 때만 let을 쓰는 방식이 가장 안전합니다.', codeTitle:'가격 계산 변수', code:'const price = 12000;\nconst count = 2;\nlet total = price * count;\n\nif (total >= 20000) {\n  total = total - 2000;\n}\n\nconsole.log(total);', details:['const는 재할당을 막아 실수를 줄여줍니다. 값이 고정되어야 하는 이름에는 const를 쓰는 것이 읽는 사람에게도 의도를 분명히 전달합니다.','let은 반복문 카운터나 계산 결과처럼 실행 중에 값이 바뀌는 경우에 사용합니다. 필요한 범위 안에서만 선언하는 습관이 좋습니다.','var는 함수 스코프와 호이스팅 때문에 초보자가 예측하기 어려운 상황을 만들 수 있습니다. 새 코드를 작성할 때는 피하는 편이 좋습니다.'], compare:[['구분','var','let','const'],['재선언','가능','불가','불가'],['재할당','가능','가능','불가'],['추천도','낮음','필요할 때','기본 선택']], checklist:['먼저 const로 선언할 수 있는지 확인하기','값이 바뀌는 경우에만 let 사용하기','새 코드에서는 var 사용을 피하기','변수 이름은 역할이 드러나게 작성하기']},
  {seq:4, slug:'react-component-intro', category:'react', publishAt:'2026-06-23T02:00:00+09:00', title:'React 컴포넌트란 무엇인가', type:'개념 설명형', doc:'react', related:[26,29], problem:'React 화면을 어디 기준으로 나눠야 하는지 감이 오지 않는 상황', summary:'컴포넌트는 화면 조각을 이름 붙여 재사용할 수 있게 만든 단위입니다. 작게 나누되, 의미 없이 쪼개지 않는 균형이 필요합니다.', codeTitle:'프로필 카드 컴포넌트', code:'function ProfileCard() {\n  return (\n    <article className="profile-card">\n      <h2>AG FE</h2>\n      <p>프론트엔드 입문 가이드</p>\n    </article>\n  );\n}\n\nexport default ProfileCard;', details:['컴포넌트는 HTML을 함수처럼 다루게 해줍니다. 같은 UI를 여러 번 쓰거나, 한 화면을 이해하기 쉬운 덩어리로 나눌 때 도움이 됩니다.','좋은 컴포넌트는 이름만 봐도 역할을 알 수 있습니다. ProfileCard, Header, PostList처럼 화면의 의미가 드러나면 유지보수가 쉬워집니다.','처음부터 너무 잘게 나누기보다 반복되거나 독립적인 역할이 보일 때 분리하는 것이 좋습니다.'], checklist:['컴포넌트 이름이 역할을 설명하는지 확인하기','반복되는 UI인지 확인하기','한 컴포넌트가 너무 많은 일을 하지 않는지 보기','props로 바꿀 데이터와 고정 구조를 구분하기']},
  {seq:5, slug:'git-github-difference', category:'git', publishAt:'2026-06-23T08:20:00+09:00', title:'Git과 GitHub 차이 쉽게 정리', type:'개념 설명형', doc:'git', related:[35,37], problem:'GitHub를 쓰면서 Git이 정확히 무엇인지 구분하지 못하는 상황', summary:'Git은 변경 기록을 관리하는 도구이고, GitHub는 그 기록을 온라인에서 저장하고 협업하게 해주는 서비스입니다.', codeTitle:'로컬과 원격 흐름', code:'git init\ngit add index.html\ngit commit -m "첫 페이지 추가"\ngit remote add origin https://github.com/user/repo.git\ngit push origin main', details:['Git은 내 컴퓨터 안에서 파일 변경 이력을 기록합니다. 언제 무엇을 바꿨는지 되돌아볼 수 있게 해주는 버전 관리 도구입니다.','GitHub는 Git 저장소를 인터넷에 올려두는 공간입니다. 혼자 백업용으로 쓸 수도 있고, 팀원이 함께 코드를 검토하는 장소로 쓸 수도 있습니다.','초보자는 Git 명령어와 GitHub 화면을 한꺼번에 배우다 보니 헷갈리기 쉽습니다. 둘을 도구와 서비스로 나눠 생각하면 훨씬 단순해집니다.'], compare:[['구분','Git','GitHub'],['정체','버전 관리 도구','저장소 호스팅 서비스'],['위치','내 컴퓨터에서도 동작','인터넷 서비스'],['주요 기능','커밋, 브랜치','푸시, PR, 이슈']], checklist:['내 컴퓨터 작업은 Git으로 기록하기','온라인 백업은 GitHub에 push하기','커밋 전 변경 파일을 확인하기','저장과 커밋을 같은 의미로 착각하지 않기']},
  {seq:6, slug:'html-div-section-article', category:'html', publishAt:'2026-06-23T13:00:00+09:00', title:'div, section, article 태그 차이 정리', type:'차이 비교형', doc:'html', related:[1,11], problem:'모든 영역을 div로만 감싸도 되는지, section과 article을 언제 써야 하는지 헷갈리는 상황', summary:'div는 의미 없는 묶음이고, section은 주제별 영역, article은 독립적으로 읽을 수 있는 콘텐츠에 가깝습니다.', codeTitle:'같은 카드 UI 비교', code:'<section class="post-section">\n  <h2>최신 글</h2>\n  <article class="post-card">\n    <h3>HTML 기본 구조</h3>\n    <p>문서의 큰 틀을 설명합니다.</p>\n  </article>\n</section>', details:['div는 스타일을 주거나 레이아웃을 잡기 위한 중립적인 태그입니다. 의미를 전달하지 않기 때문에 남발하면 문서 구조를 읽기 어려워집니다.','section은 하나의 주제를 가진 영역에 어울립니다. 보통 제목과 함께 쓰면 문서의 목차처럼 구조가 선명해집니다.','article은 블로그 글, 뉴스 기사, 카드형 게시물처럼 따로 떼어도 의미가 유지되는 콘텐츠에 적합합니다.'], compare:[['태그','의미','어울리는 상황'],['div','의미 없는 묶음','스타일/레이아웃'],['section','주제 영역','카테고리, 본문 구획'],['article','독립 콘텐츠','글, 리뷰, 카드']], checklist:['영역에 제목이 있으면 section을 고려하기','독립적으로 읽히는 콘텐츠는 article 고려하기','단순 스타일용 묶음은 div 사용하기','태그 의미보다 디자인만 보고 고르지 않기']},
  {seq:7, slug:'css-margin-padding', category:'css', publishAt:'2026-06-23T17:00:00+09:00', title:'margin과 padding 차이 이해하기', type:'차이 비교형', doc:'css', related:[2,12], problem:'여백을 넣었는데 박스 크기가 달라지거나, 옆 요소와 간격이 예상과 다르게 보이는 상황', summary:'padding은 요소 안쪽 여백이고 margin은 요소 바깥쪽 여백입니다. 카드 UI를 만들 때 이 차이를 알면 레이아웃이 안정됩니다.', codeTitle:'카드 박스 여백', code:'.card {\n  padding: 20px;\n  margin: 16px 0;\n  border: 1px solid #d8e0e8;\n}\n\n.card-title {\n  margin: 0 0 8px;\n}', details:['padding은 내용과 테두리 사이의 공간입니다. 버튼 내부 글자와 버튼 테두리 사이를 넓히고 싶을 때 padding을 씁니다.','margin은 요소와 요소 사이의 거리입니다. 카드끼리 간격을 만들거나 제목과 문단 사이를 벌릴 때 사용합니다.','초보자가 흔히 겪는 문제는 padding과 width가 함께 쓰일 때 박스 크기가 커지는 현상입니다. box-sizing을 border-box로 두면 예측하기 쉬워집니다.'], compare:[['구분','padding','margin'],['위치','테두리 안쪽','테두리 바깥쪽'],['배경색 영향','배경색이 보임','배경색이 보이지 않음'],['주 용도','내부 공간','요소 간 간격']], checklist:['글자와 테두리 사이 공간이면 padding 쓰기','요소와 요소 사이 거리면 margin 쓰기','전체 레이아웃이 밀리면 margin부터 확인하기','박스 크기가 커지면 box-sizing 확인하기']},
  {seq:8, slug:'js-function-declaration-arrow', category:'javascript', publishAt:'2026-06-23T21:00:00+09:00', title:'함수 선언식과 화살표 함수 차이', type:'차이 비교형', doc:'js', related:[3,20], problem:'function 문법과 화살표 함수가 둘 다 보여서 어떤 방식으로 작성해야 할지 모르는 상황', summary:'두 방식 모두 함수를 만들 수 있지만, 작성 위치와 this 처리 방식에서 차이가 있습니다. 초보 단계에서는 일관된 기준을 정하는 것이 좋습니다.', codeTitle:'합계 계산 함수', code:'function sum(a, b) {\n  return a + b;\n}\n\nconst multiply = (a, b) => {\n  return a * b;\n};\n\nconsole.log(sum(2, 3));\nconsole.log(multiply(2, 3));', details:['함수 선언식은 코드 아래쪽에 있어도 호출되는 경우가 많아 처음 배울 때 흐름을 놓치기 쉽습니다. 대신 전통적인 문법이라 예제가 많습니다.','화살표 함수는 짧게 쓰기 좋고 React 예제에서도 자주 등장합니다. 변수에 함수를 담는 형태라 데이터처럼 다루는 감각을 익히기 좋습니다.','둘 중 하나만 절대적으로 옳다기보다 프로젝트의 스타일에 맞추는 것이 중요합니다. 글에서는 일반 함수와 이벤트 콜백을 구분해 설명합니다.'], compare:[['구분','함수 선언식','화살표 함수'],['형태','function name()','const name = () =>'],['호출 위치','호이스팅 영향 있음','선언 후 사용 권장'],['자주 쓰는 곳','일반 함수','콜백, React 이벤트']]},
  {seq:9, slug:'react-props-state', category:'react', publishAt:'2026-06-24T02:00:00+09:00', title:'props와 state 차이 쉽게 정리', type:'차이 비교형', doc:'react', related:[4,14], problem:'부모가 내려주는 데이터와 컴포넌트 안에서 바뀌는 데이터를 구분하지 못하는 상황', summary:'props는 밖에서 들어오는 값이고 state는 컴포넌트 내부에서 변하는 값입니다. 이 차이를 알아야 React 데이터 흐름이 보입니다.', codeTitle:'사용자 카드와 좋아요 상태', code:'function UserCard({ name }) {\n  const [liked, setLiked] = React.useState(false);\n\n  return (\n    <article>\n      <h2>{name}</h2>\n      <button onClick={() => setLiked(!liked)}>\n        {liked ? "좋아요 취소" : "좋아요"}\n      </button>\n    </article>\n  );\n}', details:['props는 부모 컴포넌트가 자식에게 전달하는 입력값입니다. 자식은 받은 값을 화면에 보여주지만 직접 바꾸지는 않는다는 감각이 중요합니다.','state는 컴포넌트가 스스로 기억하는 값입니다. 버튼 클릭, 입력창 변경, 탭 전환처럼 사용자 행동에 따라 화면이 달라질 때 사용합니다.','데이터가 어디에서 시작되고 어디에서 바뀌는지 추적하면 React 오류를 훨씬 쉽게 찾을 수 있습니다.'], compare:[['구분','props','state'],['출처','부모 컴포넌트','자기 컴포넌트'],['변경 방식','부모가 변경','setState로 변경'],['예시','이름, 제목','좋아요 여부, 입력값']], checklist:['부모가 내려주는 값인지 확인하기','사용자 행동으로 바뀌는 값인지 확인하기','props를 직접 수정하지 않기','state 변경은 setter 함수로 하기']},
  {seq:10, slug:'static-dynamic-site', category:'web', publishAt:'2026-06-24T08:20:00+09:00', title:'정적 사이트와 동적 사이트 차이', type:'차이 비교형', doc:null, related:[35,39], problem:'HTML만 올린 사이트와 로그인 기능이 있는 사이트가 무엇이 다른지 헷갈리는 상황', summary:'정적 사이트는 미리 만들어진 파일을 그대로 보여주고, 동적 사이트는 요청에 따라 서버가 내용을 만들어 응답합니다.', codeTitle:'정적 페이지 예시', code:'<!-- 정적 사이트는 이 HTML 파일이 그대로 전달됩니다. -->\n<h1>AG FE Guide</h1>\n<p>프론트엔드 입문 글을 모아둔 블로그입니다.</p>', details:['정적 사이트는 HTML, CSS, JavaScript 파일을 서버에 올려두고 그대로 전달합니다. 블로그, 소개 페이지, 문서 사이트처럼 내용이 자주 변하지 않는 곳에 잘 맞습니다.','동적 사이트는 로그인 사용자, 검색 조건, 장바구니 상태처럼 매번 달라지는 정보를 서버가 처리합니다. 데이터베이스와 서버 로직이 함께 필요할 때가 많습니다.','처음 웹 배포를 배울 때는 정적 사이트부터 시작하는 것이 좋습니다. 구조가 단순하고 배포 실패 원인을 찾기 쉽기 때문입니다.'], compare:[['구분','정적 사이트','동적 사이트'],['내용 생성','미리 만든 파일','요청마다 생성 가능'],['필요 기술','HTML/CSS/JS','서버/DB 포함'],['예시','블로그, 문서','쇼핑몰, 로그인 서비스']], checklist:['로그인이나 개인화가 필요한지 확인하기','내용이 자주 바뀌는지 확인하기','처음 배포라면 정적 사이트부터 시도하기','도메인과 호스팅 연결 방식을 구분하기']},
  {seq:11, slug:'html-anchor-link-mistakes', category:'html', publishAt:'2026-06-24T13:00:00+09:00', title:'a 태그로 링크 만들 때 자주 하는 실수', type:'실수 정리형', doc:'html', related:[1,37], problem:'링크가 안 열리거나 새 창 링크, 내부 링크 경로가 예상과 다르게 동작하는 상황', summary:'a 태그는 단순해 보이지만 href 경로, 새 창 옵션, 접근성 문구를 잘못 쓰면 사용자 경험이 나빠집니다.', codeTitle:'내부 링크와 외부 링크', code:'<a href="./about.html">소개 페이지</a>\n<a href="https://developer.mozilla.org/" target="_blank" rel="noopener">MDN 열기</a>\n<a href="#content">본문으로 이동</a>', details:['내부 링크는 현재 파일 위치를 기준으로 계산됩니다. 같은 폴더인지, 하위 폴더인지에 따라 ./ 또는 ../ 사용이 달라집니다.','외부 링크를 새 창으로 열 때는 target="_blank"와 함께 rel="noopener"를 넣는 것이 좋습니다. 보안과 성능 면에서 안전한 습관입니다.','링크 문구는 여기를 클릭 같은 표현보다 이동할 목적지를 설명하는 편이 좋습니다. 검색엔진과 화면 읽기 사용자 모두에게 더 친절합니다.'], checklist:['href가 비어 있지 않은지 확인하기','상대 경로가 현재 파일 위치 기준으로 맞는지 확인하기','새 창 링크에는 rel="noopener" 넣기','링크 문구가 목적지를 설명하는지 확인하기']},
  {seq:12, slug:'css-display-block-inline', category:'css', publishAt:'2026-06-24T17:00:00+09:00', title:'display block, inline, inline-block 차이', type:'차이 비교형', doc:'css', related:[7,17], problem:'요소가 줄바꿈되거나 width가 안 먹어서 배치가 이상해지는 상황', summary:'display 속성은 요소가 한 줄을 차지하는지, 내용만큼만 차지하는지, 크기 지정이 가능한지를 결정합니다.', codeTitle:'div, span, button 배치', code:'div { display: block; width: 200px; }\nspan { display: inline; }\n.button-like {\n  display: inline-block;\n  width: 120px;\n  padding: 10px;\n}', details:['block 요소는 기본적으로 한 줄 전체를 차지합니다. div, p, h1 같은 태그가 대표적이고 레이아웃을 잡기 쉽습니다.','inline 요소는 내용만큼만 공간을 차지합니다. span, a처럼 문장 안에 자연스럽게 섞이는 요소에 어울립니다.','inline-block은 줄 안에 놓이면서 width, height, padding을 다루기 쉬워 버튼이나 작은 배지 UI에 자주 사용됩니다.'], compare:[['값','줄바꿈','크기 지정','대표 사용'],['block','발생','가능','영역 레이아웃'],['inline','없음','제한적','문장 일부'],['inline-block','없음','가능','버튼, 배지']]},
  {seq:13, slug:'js-array-map-example', category:'javascript', publishAt:'2026-06-24T21:00:00+09:00', title:'배열 map 사용법과 예제', type:'실습 예제형', doc:'js', related:[18,24], problem:'상품 목록이나 글 목록처럼 여러 데이터를 화면에 반복해서 보여주고 싶은 상황', summary:'map은 배열의 각 항목을 다른 형태로 바꿔 새 배열을 만드는 메서드입니다. 화면 목록을 만들 때 특히 많이 씁니다.', codeTitle:'상품 목록 HTML 만들기', code:'const products = ["키보드", "마우스", "모니터"];\n\nconst items = products.map((product) => {\n  return `<li>${product}</li>`;\n});\n\ndocument.querySelector("#list").innerHTML = items.join("");', details:['map은 원본 배열을 순회하면서 각 항목을 변환합니다. 문자열 배열을 HTML 문자열 배열로 바꾸거나, 데이터 객체를 화면 카드로 바꿀 때 자연스럽습니다.','map의 결과는 새 배열입니다. 단순히 콘솔에 찍기만 하려면 forEach가 어울릴 수 있지만, 변환 결과가 필요하면 map이 더 명확합니다.','React에서도 map은 목록 렌더링의 기본입니다. 이때 key를 함께 다루는 이유까지 이어서 배우면 좋습니다.'], checklist:['결과 배열이 필요한지 확인하기','콜백 함수에서 return을 빠뜨리지 않기','원본 배열을 직접 바꾸는 코드와 구분하기','화면에 넣을 때 join으로 문자열을 합치기']},
  {seq:14, slug:'react-usestate-basic', category:'react', publishAt:'2026-06-25T02:00:00+09:00', title:'useState 기본 사용법과 예제', type:'실습 예제형', doc:'react', related:[9,31], problem:'버튼을 눌렀을 때 화면의 숫자나 문구가 바뀌게 만들고 싶은 상황', summary:'useState는 React 컴포넌트가 값을 기억하고, 값이 바뀌면 화면을 다시 그리게 해주는 Hook입니다.', codeTitle:'카운터 만들기', code:'function Counter() {\n  const [count, setCount] = React.useState(0);\n\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      {count}번 클릭\n    </button>\n  );\n}', details:['useState는 현재 값과 값을 바꾸는 함수를 배열 형태로 돌려줍니다. 보통 구조 분해 문법으로 [value, setValue] 형태를 만듭니다.','값을 직접 바꾸면 React가 변화를 모를 수 있습니다. 반드시 setter 함수를 통해 상태를 변경해야 화면이 갱신됩니다.','카운터 예제는 단순하지만 입력값, 탭, 모달 열림 여부처럼 많은 UI 상태를 이해하는 출발점이 됩니다.'], checklist:['초기값이 어떤 타입인지 정하기','상태 이름과 setter 이름을 짝으로 만들기','상태를 직접 수정하지 않기','이전 값 기준 업데이트가 필요한지 확인하기']},
  {seq:15, slug:'git-commit-meaning', category:'git', publishAt:'2026-06-25T08:20:00+09:00', title:'Git commit이란 무엇인가', type:'작업 흐름형', doc:'git', related:[5,25], problem:'파일 저장과 커밋이 같은 것처럼 느껴지고, 언제 커밋해야 하는지 모르는 상황', summary:'커밋은 특정 시점의 변경 내용을 설명과 함께 기록하는 작업입니다. 저장은 파일 내용 보관이고 커밋은 변경 이력 관리입니다.', codeTitle:'add에서 commit까지', code:'git status\ngit add index.html styles.css\ngit commit -m "홈 화면 스타일 정리"\ngit log --oneline', details:['파일을 저장해도 Git 기록에는 아직 남지 않습니다. git add로 기록할 파일을 고르고, git commit으로 하나의 변경 묶음을 만듭니다.','좋은 커밋 메시지는 무엇을 왜 바꿨는지 짧게 알려줍니다. 나중에 문제를 되돌릴 때 메시지가 큰 힌트가 됩니다.','커밋은 너무 크면 검토하기 어렵고, 너무 작으면 흐름이 끊길 수 있습니다. 하나의 목적 단위로 묶는 습관이 좋습니다.'], checklist:['커밋 전 git status 확인하기','관련 있는 파일만 add하기','메시지에 변경 목적 적기','큰 작업은 기능별로 나누어 커밋하기']},
  {seq:16, slug:'html-img-not-showing', category:'html', publishAt:'2026-06-25T13:00:00+09:00', title:'img 태그 이미지가 안 보일 때 확인할 것', type:'문제 해결형', doc:'html', related:[11,36], problem:'이미지를 넣었는데 깨진 아이콘만 보이거나 배포 후 이미지가 사라지는 상황', summary:'이미지가 안 보일 때는 대부분 경로, 파일명 대소문자, 확장자, 배포 위치 문제입니다. 순서대로 확인하면 빠르게 찾을 수 있습니다.', codeTitle:'잘못된 경로와 올바른 경로', code:'<!-- 잘못된 예: 파일 위치가 다르면 깨질 수 있음 -->\n<img src="image.png" alt="예시 이미지">\n\n<!-- images 폴더 안에 있는 경우 -->\n<img src="./images/image.png" alt="예시 이미지">', details:['src는 현재 HTML 파일 위치를 기준으로 이미지를 찾습니다. 글 파일이 posts 폴더 안에 있다면 ../images처럼 한 단계 올라가야 할 수 있습니다.','로컬에서는 대소문자를 대충 써도 보이는 경우가 있지만 배포 환경에서는 Image.png와 image.png가 다른 파일로 처리될 수 있습니다.','alt는 이미지가 보이지 않을 때 대체 문구가 되고 접근성에도 중요합니다. 단순 장식이 아니라면 의미를 설명하는 문구를 넣는 것이 좋습니다.'], checklist:['이미지 파일이 실제 위치에 있는지 확인하기','src 경로가 HTML 파일 위치 기준으로 맞는지 확인하기','파일명 대소문자와 확장자 확인하기','alt 문구를 비워두지 않았는지 확인하기']},
  {seq:17, slug:'css-flex-center', category:'css', publishAt:'2026-06-25T17:00:00+09:00', title:'flex로 요소 가운데 정렬하는 방법', type:'문제 해결형', doc:'css', related:[12,22], problem:'가운데 정렬을 했는데 가로만 맞거나 세로만 맞아서 화면 중앙에 오지 않는 상황', summary:'flex 가운데 정렬은 부모 요소에 display:flex를 주고, justify-content와 align-items를 함께 이해해야 합니다.', codeTitle:'로그인 박스 중앙 배치', code:'.page-center {\n  min-height: 100vh;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n\n.login-box { width: 320px; }', details:['가운데 정렬은 자식이 아니라 부모에게 적용하는 경우가 많습니다. 부모가 flex 컨테이너가 되어야 자식 정렬 규칙이 동작합니다.','justify-content는 주축 방향 정렬이고 align-items는 교차축 방향 정렬입니다. 기본 flex-direction이 row라면 가로와 세로처럼 느껴집니다.','세로 중앙 정렬이 안 된다면 부모 높이가 충분한지 먼저 봐야 합니다. 높이가 없으면 중앙으로 보낼 공간도 없습니다.'], checklist:['정렬하려는 요소의 부모에 display:flex 넣기','부모 높이가 충분한지 확인하기','가로/세로 정렬 속성을 함께 확인하기','flex-direction을 바꿨다면 주축도 바뀌는지 확인하기']},
  {seq:18, slug:'js-foreach-map-difference', category:'javascript', publishAt:'2026-06-25T21:00:00+09:00', title:'forEach와 map 차이 이해하기', type:'차이 비교형', doc:'js', related:[13,23], problem:'둘 다 배열을 반복하는데 어느 상황에서 무엇을 써야 할지 헷갈리는 상황', summary:'forEach는 반복 실행에 가깝고 map은 새 배열을 만드는 변환에 가깝습니다. 결과값이 필요한지가 선택 기준입니다.', codeTitle:'배열 출력과 변환', code:'const names = ["HTML", "CSS", "JS"];\n\nnames.forEach((name) => console.log(name));\n\nconst labels = names.map((name) => `${name} 배우기`);\nconsole.log(labels);', details:['forEach는 각 항목에 대해 어떤 작업을 실행할 때 사용합니다. 콘솔 출력, 누적 처리, DOM 조작처럼 결과 배열이 필요하지 않은 경우입니다.','map은 각 항목을 다른 값으로 바꿔 새 배열을 만들 때 사용합니다. 원본 배열을 보존하면서 변환 결과를 다루는 데 적합합니다.','React 목록 렌더링에서는 map이 자연스럽습니다. 배열 데이터를 JSX 요소 배열로 바꾸는 작업이기 때문입니다.'], compare:[['구분','forEach','map'],['반환값','undefined','새 배열'],['목적','작업 실행','값 변환'],['추천 상황','로그 출력, 부수 효과','목록 생성, 데이터 변환']], checklist:['새 배열이 필요하면 map 쓰기','단순 실행만 필요하면 forEach 쓰기','map 안에서 return 빠뜨리지 않기','원본 배열 변경 여부 확인하기']},
  {seq:19, slug:'react-useeffect-when', category:'react', publishAt:'2026-06-26T02:00:00+09:00', title:'useEffect는 언제 사용할까', type:'상황 설명형', doc:'react', related:[14,38], problem:'컴포넌트가 렌더링된 뒤 어떤 코드를 언제 실행해야 하는지 모르는 상황', summary:'useEffect는 화면 렌더링 이후 외부 시스템과 맞춰야 하는 작업에 사용합니다. 데이터 요청, 문서 제목 변경, 구독 정리에 자주 쓰입니다.', codeTitle:'문서 제목 변경', code:'function PageTitle({ title }) {\n  React.useEffect(() => {\n    document.title = title;\n  }, [title]);\n\n  return <h1>{title}</h1>;\n}', details:['useEffect는 렌더링 결과가 화면에 반영된 뒤 실행됩니다. 그래서 브라우저 API, 네트워크 요청, 외부 라이브러리 연결 같은 작업에 적합합니다.','의존성 배열은 effect가 다시 실행되는 기준입니다. 배열을 잘못 쓰면 너무 자주 실행되거나 필요한 순간에 실행되지 않을 수 있습니다.','모든 로직을 useEffect에 넣는 것은 좋지 않습니다. 화면 계산만으로 해결되는 값은 렌더링 중 계산하는 편이 더 단순합니다.'], compare:[['상황','useEffect 필요성'],['문서 제목 변경','필요'],['API 데이터 요청','대체로 필요'],['단순 합계 계산','불필요'],['이벤트 구독 정리','필요']], checklist:['외부 시스템과 연결되는 작업인지 확인하기','의존성 배열에 필요한 값을 넣기','정리 함수가 필요한지 확인하기','단순 계산을 effect로 옮기지 않기']},
  {seq:20, slug:'domain-hosting-difference', category:'web', publishAt:'2026-06-26T08:20:00+09:00', title:'도메인과 호스팅 차이 쉽게 정리', type:'개념 흐름형', doc:null, related:[10,30], problem:'도메인을 샀는데 이것만으로 사이트가 열리는지, 호스팅과 무엇이 다른지 헷갈리는 상황', summary:'도메인은 주소이고 호스팅은 사이트 파일이 놓이는 공간입니다. DNS는 주소가 어느 공간을 가리킬지 연결해줍니다.', codeTitle:'DNS 흐름 예시', code:'ag-fe.com\n  -> DNS 레코드 확인\n  -> Cloudflare Worker 또는 Pages\n  -> HTML/CSS/JavaScript 응답', details:['도메인은 사람이 기억하기 쉬운 주소입니다. ag-fe.com처럼 입력하면 브라우저가 실제 서버 위치를 찾아가야 합니다.','호스팅은 사이트 파일을 제공하는 공간입니다. GitHub Pages, Cloudflare Pages, Netlify, Vercel 등이 정적 사이트 호스팅 역할을 할 수 있습니다.','DNS는 도메인과 호스팅을 이어주는 안내판입니다. A, CNAME, Worker 라우트 같은 설정이 여기에서 사용됩니다.'], compare:[['구분','역할','예시'],['도메인','주소','ag-fe.com'],['호스팅','파일 제공 공간','Cloudflare Pages'],['DNS','주소 연결 설정','CNAME, A 레코드']], checklist:['도메인만 사고 호스팅을 연결했는지 확인하기','DNS 레코드가 어디를 가리키는지 확인하기','www 주소도 연결할지 결정하기','HTTPS 인증서가 정상인지 확인하기']},
  {seq:21, slug:'html-input-label', category:'html', publishAt:'2026-06-26T13:00:00+09:00', title:'input과 label 태그 기본 사용법', type:'실습 예제형', doc:'html', related:[6,31], problem:'입력창 옆 문구를 클릭해도 입력창이 선택되지 않고, 폼 구조가 어색한 상황', summary:'label은 입력창의 이름표 역할을 합니다. for와 id를 연결하면 사용성과 접근성이 함께 좋아집니다.', codeTitle:'로그인 입력 폼', code:'<label for="email">이메일</label>\n<input id="email" name="email" type="email" autocomplete="email">\n\n<label for="password">비밀번호</label>\n<input id="password" name="password" type="password">', details:['label의 for 값과 input의 id 값이 같으면 라벨을 클릭했을 때 해당 입력창으로 포커스가 이동합니다. 작은 차이지만 폼 사용성이 좋아집니다.','input의 type은 브라우저가 입력값을 어떻게 다룰지 알려줍니다. email, password, number처럼 목적에 맞는 타입을 쓰면 모바일 키보드도 더 알맞게 나옵니다.','name은 서버로 제출될 때 데이터 이름이 됩니다. 화면만 만들 때도 나중을 생각해 의미 있는 name을 붙이는 습관이 좋습니다.'], checklist:['label for와 input id가 같은지 확인하기','입력 목적에 맞는 type 사용하기','name 속성을 의미 있게 작성하기','비밀번호 입력은 type="password" 사용하기']},
  {seq:22, slug:'css-justify-align', category:'css', publishAt:'2026-06-26T17:00:00+09:00', title:'justify-content와 align-items 차이', type:'차이 비교형', doc:'css', related:[17,36], problem:'flex 정렬에서 어떤 속성이 가로이고 어떤 속성이 세로인지 매번 헷갈리는 상황', summary:'justify-content는 주축 정렬, align-items는 교차축 정렬입니다. flex-direction을 바꾸면 기준 축도 함께 바뀝니다.', codeTitle:'메뉴 버튼 정렬', code:'.nav {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n\n.nav-actions { display: flex; gap: 8px; }', details:['기본 flex-direction은 row입니다. 이때 justify-content는 가로 방향 정렬처럼 보이고 align-items는 세로 방향 정렬처럼 보입니다.','flex-direction을 column으로 바꾸면 주축이 세로가 됩니다. 그래서 justify-content가 세로 정렬처럼 동작할 수 있습니다.','정렬이 헷갈릴 때는 먼저 주축이 어느 방향인지 확인하는 습관이 좋습니다. 속성 이름만 외우면 방향이 바뀔 때 다시 막힙니다.'], compare:[['속성','정렬 기준','row일 때 느낌'],['justify-content','주축','가로 정렬'],['align-items','교차축','세로 정렬'],['gap','아이템 사이 간격','방향과 함께 적용']], checklist:['display:flex가 부모에 있는지 확인하기','flex-direction이 row인지 column인지 확인하기','주축 기준으로 justify-content 이해하기','아이템 사이 간격은 gap으로 처리하기']},
  {seq:23, slug:'js-filter-find', category:'javascript', publishAt:'2026-06-26T21:00:00+09:00', title:'filter와 find 차이 정리', type:'차이 비교형', doc:'js', related:[18,33], problem:'조건에 맞는 데이터를 찾을 때 filter와 find 중 무엇을 써야 할지 모르는 상황', summary:'filter는 조건에 맞는 모든 항목을 배열로 돌려주고, find는 처음 만나는 하나의 항목만 돌려줍니다.', codeTitle:'게시글 목록 검색', code:'const posts = [\n  { id: 1, category: "css" },\n  { id: 2, category: "js" },\n  { id: 3, category: "css" }\n];\n\nconst cssPosts = posts.filter((post) => post.category === "css");\nconst firstCssPost = posts.find((post) => post.category === "css");', details:['filter는 조건에 맞는 항목이 여러 개일 수 있다는 전제로 사용합니다. 결과는 항상 배열이므로 길이가 0일 수도 있습니다.','find는 하나만 필요할 때 사용합니다. 조건에 맞는 항목이 없으면 undefined가 나오므로 이후 코드에서 확인이 필요합니다.','검색 결과 목록을 만들 때는 filter가, id로 특정 게시글 하나를 찾을 때는 find가 어울립니다.'], compare:[['구분','filter','find'],['결과','배열','항목 하나 또는 undefined'],['사용 목적','여러 개 찾기','첫 번째 하나 찾기'],['예시','카테고리 글 목록','id로 상세 글 찾기']], checklist:['결과가 여러 개인지 하나인지 먼저 정하기','find 결과가 undefined일 수 있음을 처리하기','filter 결과가 빈 배열일 수 있음을 처리하기','조건 함수가 true/false를 반환하는지 확인하기']},
  {seq:24, slug:'react-map-list-rendering', category:'react', publishAt:'2026-06-27T02:00:00+09:00', title:'React에서 map으로 목록 출력하기', type:'실습 예제형', doc:'react', related:[13,4], problem:'배열 데이터를 React 화면에 반복 출력하고 싶은데 key 경고가 나오는 상황', summary:'React에서 배열을 화면에 보여줄 때 map을 사용합니다. 각 항목에는 안정적인 key를 넣어 React가 변화를 추적하게 해야 합니다.', codeTitle:'할 일 목록', code:'function TodoList() {\n  const todos = [\n    { id: 1, text: "HTML 복습" },\n    { id: 2, text: "CSS 정렬 연습" }\n  ];\n\n  return <ul>{todos.map((todo) => <li key={todo.id}>{todo.text}</li>)}</ul>;\n}', details:['map은 데이터 배열을 JSX 배열로 바꾸는 역할을 합니다. 데이터가 늘어나면 화면 항목도 자연스럽게 늘어납니다.','key는 React가 어떤 항목이 추가, 수정, 삭제되었는지 구분하는 단서입니다. 가능하면 배열 인덱스보다 고유 id를 사용하는 것이 좋습니다.','목록 렌더링을 익히면 게시글 목록, 상품 카드, 댓글 목록처럼 많은 UI를 같은 방식으로 만들 수 있습니다.'], checklist:['map 안에서 JSX를 return하는지 확인하기','각 항목에 key 넣기','key로 배열 인덱스를 남용하지 않기','데이터 구조와 화면 구조를 분리해서 생각하기']},
  {seq:25, slug:'git-branch-when', category:'git', publishAt:'2026-06-27T08:20:00+09:00', title:'Git branch는 언제 사용할까', type:'작업 흐름형', doc:'git', related:[15,35], problem:'main 브랜치 하나로만 작업하다가 실험 코드와 정상 코드가 섞이는 상황', summary:'브랜치는 작업 흐름을 나누는 가지입니다. 새 기능, 수정, 실험을 main과 분리하면 안전하게 작업할 수 있습니다.', codeTitle:'main과 feature 브랜치', code:'git branch\ngit switch -c feature/header\n# 파일 수정 후\ngit add .\ngit commit -m "헤더 메뉴 개선"\ngit switch main', details:['main 브랜치는 보통 안정적인 상태를 유지하는 기준점입니다. 바로 배포되는 저장소라면 더 조심해서 다뤄야 합니다.','새 기능을 만들 때 별도 브랜치를 쓰면 작업 도중 문제가 생겨도 main에 바로 영향을 주지 않습니다.','작업이 끝나면 Pull Request나 merge를 통해 main으로 합칩니다. 혼자 작업할 때도 브랜치를 쓰면 변경 내용을 정리하기 쉽습니다.'], compare:[['상황','브랜치 사용 추천'],['간단한 오타 수정','선택'],['새 기능 개발','추천'],['실험 코드','강력 추천'],['배포 중인 main 수정','주의']], checklist:['작업 시작 전 현재 브랜치 확인하기','새 기능은 feature 브랜치로 나누기','커밋 후 main에 합칠지 판단하기','불필요한 브랜치는 정리하기']},
  {seq:26, slug:'html-form-when', category:'html', publishAt:'2026-06-27T13:00:00+09:00', title:'form 태그는 언제 사용해야 할까', type:'흐름 설명형', doc:'html', related:[21,37], problem:'입력창과 버튼은 만들었지만 form으로 감싸야 하는지 판단하지 못하는 상황', summary:'form은 사용자가 입력한 값을 하나의 제출 단위로 묶는 태그입니다. 검색, 로그인, 문의처럼 입력을 보내는 흐름에 적합합니다.', codeTitle:'검색 폼과 문의 폼', code:'<form action="/search" method="get">\n  <label for="keyword">검색어</label>\n  <input id="keyword" name="q">\n  <button type="submit">검색</button>\n</form>', details:['form은 입력 요소들을 의미 있는 그룹으로 묶습니다. 버튼을 누르거나 Enter를 눌렀을 때 제출 흐름을 자연스럽게 처리할 수 있습니다.','action은 데이터를 보낼 주소이고 method는 보내는 방식입니다. 검색처럼 주소에 조건이 보여도 되는 경우 get을 자주 씁니다.','JavaScript로 제출을 가로채는 경우에도 form 구조를 유지하면 접근성과 기본 동작을 활용할 수 있습니다.'], compare:[['속성','역할','예시'],['action','제출 주소','/search'],['method','전송 방식','get, post'],['name','전송 이름','q, email']], checklist:['입력값을 제출하는 흐름인지 확인하기','button type을 명확히 지정하기','input에 name 속성 넣기','label과 input 연결하기']},
  {seq:27, slug:'css-position-relative-absolute', category:'css', publishAt:'2026-06-27T17:00:00+09:00', title:'position relative와 absolute 차이', type:'문제 해결형', doc:'css', related:[32,17], problem:'absolute를 썼더니 요소가 예상하지 못한 위치로 날아가는 상황', summary:'relative는 자기 위치를 기준으로 조정하고, absolute는 가장 가까운 위치 기준 부모를 찾아 배치됩니다.', codeTitle:'배지 위치 잡기', code:'.card { position: relative; }\n.badge {\n  position: absolute;\n  top: 12px;\n  right: 12px;\n}', details:['relative는 원래 자리의 흐름을 유지한 채 위치를 조금 조정합니다. 단독으로 쓰기보다 absolute 자식의 기준점으로 자주 사용됩니다.','absolute는 문서 흐름에서 빠져나와 기준 부모 안에서 배치됩니다. 부모 중 position이 static이 아닌 요소를 기준으로 삼습니다.','카드 안 오른쪽 위 배지처럼 특정 영역 안에 고정하고 싶은 요소는 부모에 relative, 자식에 absolute를 주면 안정적입니다.'], compare:[['구분','relative','absolute'],['문서 흐름','유지','빠짐'],['기준','자기 원래 위치','위치 기준 부모'],['대표 사용','기준점 만들기','배지, 툴팁']], checklist:['absolute 자식의 부모에 position:relative가 있는지 확인하기','top/right/bottom/left 기준을 명확히 하기','겹침이 생기면 z-index도 함께 확인하기','레이아웃 전체를 absolute로 만들지 않기']},
  {seq:28, slug:'js-if-ternary', category:'javascript', publishAt:'2026-06-27T21:00:00+09:00', title:'if문과 삼항연산자 사용 기준', type:'사용 기준형', doc:'js', related:[8,29], problem:'조건문을 짧게 쓰려다가 코드가 오히려 읽기 어려워지는 상황', summary:'if문은 흐름이 복잡할 때 좋고, 삼항연산자는 간단한 값 선택에 좋습니다. 짧다고 항상 좋은 코드는 아닙니다.', codeTitle:'로그인 상태 문구', code:'const isLoggedIn = true;\n\nconst message = isLoggedIn ? "환영합니다" : "로그인이 필요합니다";\n\nif (!isLoggedIn) {\n  console.log("로그인 페이지로 이동합니다.");\n}', details:['삼항연산자는 조건에 따라 값 하나를 고를 때 간결합니다. 버튼 문구, 클래스 이름, 간단한 표시 텍스트에 잘 맞습니다.','if문은 여러 줄의 작업이 필요하거나 조건 분기가 복잡할 때 더 읽기 쉽습니다. 특히 early return 패턴과 함께 쓰면 흐름이 선명해집니다.','중첩 삼항연산자는 초보자뿐 아니라 숙련자에게도 읽기 어렵습니다. 두 번 이상 겹치면 if문으로 바꾸는 편이 좋습니다.'], compare:[['상황','추천'],['값 하나 선택','삼항연산자'],['여러 작업 실행','if문'],['조건이 3개 이상','if문'],['JSX 안 짧은 표시','삼항연산자 가능']], checklist:['조건 결과가 값 하나인지 확인하기','삼항연산자가 한 줄을 넘겨 복잡해지면 if문 고려하기','중첩 삼항연산자 피하기','읽는 사람이 바로 이해할 수 있는지 확인하기']},
  {seq:29, slug:'react-conditional-rendering', category:'react', publishAt:'2026-06-28T02:00:00+09:00', title:'조건부 렌더링 쉽게 이해하기', type:'문제 해결형', doc:'react', related:[28,32], problem:'로그인 여부나 데이터 상태에 따라 다른 화면을 보여주고 싶은 상황', summary:'조건부 렌더링은 조건에 따라 JSX를 다르게 반환하는 방식입니다. React 화면을 상황별로 나누는 기본 기술입니다.', codeTitle:'로그인/로그아웃 화면', code:'function LoginMessage({ isLoggedIn }) {\n  if (isLoggedIn) {\n    return <p>다시 오신 것을 환영합니다.</p>;\n  }\n\n  return <button>로그인하기</button>;\n}', details:['React에서는 JavaScript 조건문을 사용해 화면을 바꿉니다. if문, 삼항연산자, && 연산자 모두 상황에 따라 사용할 수 있습니다.','조건이 복잡하면 JSX 안에 모두 넣기보다 위쪽에서 변수로 분리하거나 별도 컴포넌트로 나누면 읽기 쉽습니다.','로딩, 에러, 빈 데이터, 정상 데이터처럼 상태가 여러 개인 화면은 조건 순서를 명확히 정해야 합니다.'], compare:[['방식','어울리는 상황'],['if문 return','분기가 큰 화면'],['삼항연산자','짧은 둘 중 하나'],['&& 연산자','있으면 보여주기'],['별도 컴포넌트','화면이 커질 때']], checklist:['조건의 기준 값이 무엇인지 정하기','로딩/에러/빈 상태를 따로 고려하기','JSX 안 조건이 너무 길면 분리하기','false일 때 아무것도 안 보여도 되는지 확인하기']},
  {seq:30, slug:'why-https-matters', category:'web', publishAt:'2026-06-28T08:20:00+09:00', title:'HTTPS가 필요한 이유', type:'보안 설명형', doc:null, related:[20,37], problem:'http와 https 차이를 단순히 주소창 자물쇠 정도로만 이해하는 상황', summary:'HTTPS는 브라우저와 사이트 사이의 통신을 암호화합니다. 로그인, 입력 폼, 검색엔진 신뢰도에서 중요한 기본 조건입니다.', codeTitle:'로그인 페이지 예시', code:'<!-- HTTPS 환경에서 제공되어야 안전한 입력 예시 -->\n<form>\n  <label for="email">이메일</label>\n  <input id="email" type="email">\n  <label for="password">비밀번호</label>\n  <input id="password" type="password">\n</form>', details:['HTTP 통신은 중간에서 내용을 엿보거나 조작할 위험이 있습니다. HTTPS는 인증서와 암호화를 통해 이런 위험을 줄입니다.','브라우저는 입력 폼이 있는 HTTP 페이지를 안전하지 않다고 표시할 수 있습니다. 사용자가 사이트를 신뢰하는 데 직접적인 영향을 줍니다.','요즘 배포 서비스는 HTTPS를 자동으로 제공하는 경우가 많습니다. 도메인을 연결한 뒤 인증서가 정상 발급되었는지 확인하는 습관이 필요합니다.'], compare:[['구분','HTTP','HTTPS'],['암호화','없음','있음'],['주소 표시','주의 표시 가능','자물쇠/보안 연결'],['추천','테스트 외 비추천','기본 사용']], checklist:['도메인 접속이 https로 열리는지 확인하기','www와 루트 도메인 모두 확인하기','인증서 오류가 없는지 확인하기','폼이 있는 페이지는 반드시 HTTPS로 제공하기']},
  {seq:31, slug:'css-z-index-not-working', category:'css', publishAt:'2026-06-28T13:00:00+09:00', title:'z-index가 적용되지 않을 때 확인할 것', type:'원인 분석형', doc:'css', related:[27,17], problem:'z-index 값을 크게 줬는데도 모달이나 메뉴가 다른 요소 뒤에 가려지는 상황', summary:'z-index는 숫자만 크게 준다고 항상 이기지 않습니다. position과 stacking context를 함께 봐야 합니다.', codeTitle:'모달과 배경 레이어', code:'.overlay {\n  position: fixed;\n  inset: 0;\n  background: rgba(0,0,0,.4);\n  z-index: 10;\n}\n.modal {\n  position: fixed;\n  z-index: 20;\n}', details:['z-index는 position이 적용된 요소에서 의미 있게 동작하는 경우가 많습니다. static 상태에서는 기대처럼 작동하지 않을 수 있습니다.','부모 요소가 새로운 쌓임 맥락을 만들면 자식의 z-index가 아무리 커도 부모 바깥 요소를 이기지 못할 수 있습니다.','모달, 드롭다운, 고정 헤더는 겹침 문제가 자주 생깁니다. 레이어 순서를 미리 정해두면 유지보수가 편합니다.'], checklist:['position 값이 static이 아닌지 확인하기','부모 요소가 stacking context를 만드는지 확인하기','z-index 숫자 체계를 정해두기','모달과 오버레이 순서를 함께 테스트하기']},
  {seq:32, slug:'js-undefined-null', category:'javascript', publishAt:'2026-06-28T17:00:00+09:00', title:'undefined와 null 차이 쉽게 이해하기', type:'차이 비교형', doc:'js', related:[23,38], problem:'값이 없다는 의미가 둘로 나뉘어 에러 원인을 찾기 어려운 상황', summary:'undefined는 아직 값이 정해지지 않은 상태에 가깝고, null은 의도적으로 비워둔 값에 가깝습니다.', codeTitle:'사용자 정보 객체', code:'let selectedUser;\nconsole.log(selectedUser); // undefined\n\nselectedUser = null;\nconsole.log(selectedUser); // null\n\nconst user = { name: "AG FE", email: null };', details:['undefined는 변수를 선언했지만 값을 넣지 않았거나, 객체에 없는 속성을 읽을 때 자주 나타납니다. 개발자가 의도하지 않은 상황일 수 있습니다.','null은 비어 있음을 명시적으로 표현할 때 사용합니다. 예를 들어 아직 선택된 사용자가 없다는 상태를 일부러 나타낼 수 있습니다.','API 데이터에서는 null이 자주 등장합니다. 화면에 출력하기 전에 null과 undefined를 모두 고려하면 예외를 줄일 수 있습니다.'], compare:[['구분','undefined','null'],['의미','아직 값 없음','의도적 비움'],['발생','미할당, 없는 속성','직접 지정'],['처리','기본값 고려','빈 상태 처리']], checklist:['객체 속성을 읽기 전 존재 여부 확인하기','API 응답에서 null 가능성 확인하기','기본값이 필요한지 정하기','빈 상태 문구를 준비하기']},
  {seq:33, slug:'js-queryselector-basic', category:'javascript', publishAt:'2026-06-28T21:00:00+09:00', title:'querySelector로 HTML 요소 선택하는 방법', type:'실습 예제형', doc:'js', related:[23,21], problem:'JavaScript로 버튼이나 문구를 찾아 바꾸고 싶은데 선택자 작성이 헷갈리는 상황', summary:'querySelector는 CSS 선택자 문법으로 HTML 요소 하나를 선택합니다. 선택자 기본기를 알면 DOM 조작이 쉬워집니다.', codeTitle:'버튼과 문구 선택', code:'const button = document.querySelector(".change-button");\nconst message = document.querySelector("#message");\n\nbutton.addEventListener("click", () => {\n  message.textContent = "문구가 바뀌었습니다.";\n});', details:['querySelector는 조건에 맞는 첫 번째 요소를 돌려줍니다. 여러 개를 모두 선택하려면 querySelectorAll을 사용합니다.','선택자는 CSS와 같은 방식입니다. class는 .name, id는 #name, 태그는 button처럼 작성합니다.','선택 결과가 null일 수 있으므로 스크립트 실행 시점과 HTML 구조를 함께 확인해야 합니다.'], checklist:['class 선택자 앞에 점을 붙였는지 확인하기','id 선택자 앞에 #을 붙였는지 확인하기','요소가 실제로 HTML에 있는지 확인하기','script가 DOM 생성 후 실행되는지 확인하기']},
  {seq:34, slug:'react-input-state', category:'react', publishAt:'2026-06-29T02:00:00+09:00', title:'input 값을 state로 관리하는 방법', type:'실습 예제형', doc:'react', related:[14,21], problem:'입력창에 적은 값을 React 화면에 바로 반영하고 싶은 상황', summary:'React에서는 input의 value를 state와 연결하고, onChange에서 state를 업데이트해 입력값을 관리합니다.', codeTitle:'이름 입력 미리보기', code:'function NameForm() {\n  const [name, setName] = React.useState("");\n\n  return (\n    <div>\n      <input value={name} onChange={(e) => setName(e.target.value)} />\n      <p>입력한 이름: {name}</p>\n    </div>\n  );\n}', details:['입력값을 state로 관리하면 화면의 다른 부분에서 같은 값을 즉시 사용할 수 있습니다. 미리보기, 검증 메시지, 제출 데이터 구성에 유용합니다.','value만 넣고 onChange를 빼면 읽기 전용처럼 동작할 수 있습니다. 입력 가능한 controlled input에는 두 속성이 함께 필요합니다.','폼이 커지면 각 입력값을 개별 state로 둘지 객체 하나로 관리할지 선택해야 합니다. 처음에는 단순한 구조부터 시작하는 것이 좋습니다.'], checklist:['input value와 state를 연결하기','onChange에서 setter 호출하기','이벤트 객체의 target.value 사용하기','빈 문자열 초기값을 준비하기']},
  {seq:35, slug:'github-pages-static-deploy', category:'git', publishAt:'2026-06-29T08:20:00+09:00', title:'GitHub Pages로 정적 사이트 배포하기', type:'단계별 가이드형', doc:'github', related:[5,25], problem:'HTML 파일을 만들었지만 인터넷 주소로 접속하게 만드는 방법을 모르는 상황', summary:'GitHub Pages는 정적 파일을 저장소에서 바로 공개할 수 있는 기능입니다. 간단한 HTML/CSS 사이트 배포 연습에 좋습니다.', codeTitle:'정적 HTML 배포 흐름', code:'git add index.html styles.css\ngit commit -m "정적 사이트 추가"\ngit push origin main\n# GitHub 저장소 Settings > Pages에서 배포 소스 선택', details:['GitHub Pages는 서버 코드를 실행하는 서비스가 아니라 정적 파일을 공개하는 기능입니다. HTML, CSS, JavaScript 파일 중심 사이트에 잘 맞습니다.','저장소 Settings의 Pages 메뉴에서 브랜치와 폴더를 선택하면 배포 주소가 만들어집니다. 설정 후 실제 반영까지 시간이 걸릴 수 있습니다.','커스텀 도메인을 연결하려면 DNS 설정도 필요합니다. 이때 GitHub Pages와 Cloudflare Pages 같은 다른 배포 방식이 섞이지 않도록 주의해야 합니다.'], checklist:['저장소에 index.html이 있는지 확인하기','Pages 소스 브랜치가 맞는지 확인하기','배포 주소가 열릴 때까지 기다리기','커스텀 도메인 DNS가 올바른지 확인하기']},
  {seq:36, slug:'css-media-query-responsive', category:'css', publishAt:'2026-06-29T13:00:00+09:00', title:'media query로 반응형 웹 만들기', type:'실습 예제형', doc:'css', related:[16,22], problem:'PC에서는 괜찮은 레이아웃이 모바일에서 너무 좁거나 깨지는 상황', summary:'media query는 화면 크기나 환경에 따라 다른 CSS를 적용하게 해줍니다. 모바일 대응의 기본 도구입니다.', codeTitle:'2단 카드에서 1단 카드로', code:'.card-grid {\n  display: grid;\n  grid-template-columns: repeat(2, 1fr);\n  gap: 16px;\n}\n\n@media (max-width: 640px) {\n  .card-grid { grid-template-columns: 1fr; }\n}', details:['반응형 웹은 화면 크기가 달라져도 읽기와 조작이 편해야 합니다. 단순히 줄어드는 것이 아니라 구조가 바뀌어야 할 때가 있습니다.','media query는 특정 조건에서 CSS를 덮어씁니다. 보통 큰 화면 기본 스타일을 작성하고 작은 화면 조건에서 단순한 레이아웃으로 바꿉니다.','모바일에서는 글자 크기, 버튼 간격, 가로 스크롤 여부를 꼭 확인해야 합니다. 레이아웃만 맞고 터치가 어려우면 좋은 반응형이라고 보기 어렵습니다.'], checklist:['모바일에서 가로 스크롤이 생기는지 확인하기','그리드 열 개수를 줄일 기준 정하기','버튼과 링크 간격이 충분한지 확인하기','이미지와 코드 블록이 부모 너비를 넘지 않게 하기']},
  {seq:37, slug:'js-addeventlistener-click', category:'javascript', publishAt:'2026-06-29T17:00:00+09:00', title:'addEventListener로 클릭 이벤트 만들기', type:'실습 예제형', doc:'js', related:[33,14], problem:'버튼을 눌렀을 때 숫자나 문구가 바뀌는 동작을 만들고 싶은 상황', summary:'addEventListener는 특정 이벤트가 발생했을 때 실행할 함수를 등록합니다. 클릭, 입력, 제출 같은 상호작용의 기본입니다.', codeTitle:'카운터 버튼', code:'const button = document.querySelector("#countButton");\nconst output = document.querySelector("#countOutput");\nlet count = 0;\n\nbutton.addEventListener("click", () => {\n  count += 1;\n  output.textContent = `${count}번 클릭했습니다.`;\n});', details:['이벤트는 사용자의 행동이나 브라우저 상태 변화를 의미합니다. click 이벤트는 버튼, 링크, 카드 등에서 가장 먼저 연습하기 좋습니다.','addEventListener의 첫 번째 값은 이벤트 이름이고 두 번째 값은 실행할 함수입니다. 함수 이름만 넘길 수도 있고, 짧은 화살표 함수를 바로 넣을 수도 있습니다.','요소 선택이 실패하면 이벤트 등록도 실패합니다. HTML이 먼저 만들어진 뒤 스크립트가 실행되는지 확인해야 합니다.'], checklist:['선택한 요소가 null이 아닌지 확인하기','이벤트 이름 철자가 맞는지 확인하기','함수를 호출하지 말고 함수 자체를 전달하기','상태 값이 필요한 경우 변수 위치를 확인하기']},
  {seq:38, slug:'js-fetch-api-basic', category:'javascript', publishAt:'2026-06-29T21:00:00+09:00', title:'fetch로 API 데이터 가져오는 기본 방법', type:'흐름 설명형', doc:'js', related:[19,32], problem:'외부 데이터 주소에서 JSON을 가져오고 화면에 보여주고 싶은 상황', summary:'fetch는 네트워크 요청을 보내는 Web API입니다. 응답을 받은 뒤 JSON으로 변환하고 필요한 데이터를 사용합니다.', codeTitle:'JSON 데이터 호출', code:'async function loadPost() {\n  const response = await fetch("https://jsonplaceholder.typicode.com/posts/1");\n  const data = await response.json();\n  console.log(data.title);\n}\n\nloadPost();', details:['fetch는 요청을 보낸 뒤 Promise를 돌려줍니다. async/await 문법을 함께 쓰면 순서대로 읽기 쉬운 코드가 됩니다.','응답 자체와 실제 JSON 데이터는 다릅니다. response.json()을 호출해야 JavaScript 객체처럼 다룰 수 있습니다.','네트워크 요청은 실패할 수 있습니다. 실제 서비스 코드에서는 로딩 상태, 에러 처리, 빈 데이터 처리까지 함께 고려해야 합니다.'], checklist:['요청 주소가 올바른지 확인하기','await response.json()을 빠뜨리지 않기','네트워크 실패 가능성 고려하기','받은 데이터 구조를 console.log로 먼저 확인하기']},
  {seq:39, slug:'react-click-event', category:'react', publishAt:'2026-06-30T02:00:00+09:00', title:'React에서 버튼 클릭 이벤트 처리하기', type:'실수 정리형', doc:'react', related:[29,37], problem:'React 버튼에서 함수를 넘겼는데 렌더링 순간 바로 실행되거나 값이 바뀌지 않는 상황', summary:'React 이벤트는 JSX 속성에 함수로 전달합니다. 함수를 즉시 호출하는지, 클릭 때 실행할 함수로 넘기는지 구분해야 합니다.', codeTitle:'좋아요 버튼', code:'function LikeButton() {\n  const [liked, setLiked] = React.useState(false);\n\n  return (\n    <button onClick={() => setLiked(!liked)}>\n      {liked ? "좋아요 취소" : "좋아요"}\n    </button>\n  );\n}', details:['onClick={handleClick}은 클릭했을 때 함수를 실행하라는 뜻입니다. onClick={handleClick()}처럼 괄호를 붙이면 렌더링 중 바로 실행될 수 있습니다.','인자를 넘겨야 한다면 화살표 함수로 감싸는 방식이 안전합니다. onClick={() => handleClick(id)}처럼 작성하면 클릭 때 실행됩니다.','상태를 바꾸는 이벤트에서는 이전 상태와 새 상태의 관계를 분명히 해야 합니다. 단순 토글은 !값으로도 가능하지만 복잡하면 함수형 업데이트를 고려합니다.'], checklist:['onClick에 함수 실행 결과가 아니라 함수를 넘겼는지 확인하기','인자가 필요하면 화살표 함수로 감싸기','상태 변경은 setter 함수 사용하기','버튼 문구가 상태에 맞게 바뀌는지 확인하기']},
  {seq:40, slug:'react-beginner-errors', category:'react', publishAt:'2026-06-30T08:20:00+09:00', title:'React 초보자가 자주 만나는 에러 정리', type:'체크리스트형', doc:'react', related:[19,39], problem:'빨간 에러가 나오지만 import, key, state 수정 중 어디가 문제인지 판단하기 어려운 상황', summary:'React 초보 에러는 대부분 컴포넌트 이름, import/export, key, state 수정 방식에서 시작됩니다. 자주 보는 패턴을 알면 당황이 줄어듭니다.', codeTitle:'key와 import 오류 확인', code:'// 목록에는 key가 필요합니다.\nitems.map((item) => <li key={item.id}>{item.name}</li>);\n\n// default export라면 이름을 자유롭게 가져올 수 있습니다.\nimport Header from "./Header";', details:['컴포넌트 이름은 대문자로 시작해야 합니다. 소문자로 시작하면 React가 일반 HTML 태그처럼 해석할 수 있습니다.','목록을 렌더링할 때 key가 없으면 경고가 나타납니다. 경고라고 무시하기보다 데이터 변경 시 화면이 꼬이지 않게 고유한 key를 넣는 것이 좋습니다.','state를 직접 수정하면 화면이 갱신되지 않거나 예측하기 어려운 버그가 생깁니다. 배열과 객체도 새 값으로 만들어 setter에 전달해야 합니다.'], checklist:['컴포넌트 이름이 대문자로 시작하는지 확인하기','import/export 방식이 맞는지 확인하기','map 목록에 안정적인 key 넣기','state를 직접 수정하지 않았는지 확인하기','에러 메시지의 파일명과 줄 번호 먼저 보기']}
];

function agNow() { return new Date(); }
function agDate(value) { return new Date(value); }
function agPublished(post) { return agDate(post.publishAt) <= agNow(); }
function agFormatDate(value) {
  return agDate(value).toLocaleString('ko-KR', { timeZone:'Asia/Seoul', month:'numeric', day:'numeric', hour:'2-digit', minute:'2-digit' });
}
function agPostUrl(post) { return `./post.html?slug=${encodeURIComponent(post.slug)}`; }
function agEscape(value) {
  return String(value).replace(/[&<>"']/g, function (char) {
    return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char];
  });
}
function agPostBySeq(seq) { return AG_POSTS.find(function (post) { return post.seq === seq; }); }
function agPostBySlug(slug) { return AG_POSTS.find(function (post) { return post.slug === slug; }); }
function agPublishedPosts() { return AG_POSTS.filter(agPublished).sort(function (a, b) { return agDate(b.publishAt) - agDate(a.publishAt); }); }

function agCard(post) {
  return `<article class="post-card" data-publish-at="${post.publishAt}">
    <span class="meta">${AG_CATEGORIES[post.category]} · ${agFormatDate(post.publishAt)}</span>
    <h3><a href="${agPostUrl(post)}">${post.title}</a></h3>
    <p>${post.summary}</p>
  </article>`;
}

function agRenderLists() {
  document.querySelectorAll('[data-post-list]').forEach(function (target) {
    const kind = target.getAttribute('data-post-list');
    const category = target.getAttribute('data-post-category');
    let posts = agPublishedPosts();
    if (category) posts = posts.filter(function (post) { return post.category === category; });
    if (kind === 'latest') posts = posts.slice(0, 12);
    target.innerHTML = posts.length ? posts.map(agCard).join('') : '<p class="empty-note">아직 공개된 글이 없습니다. 예약 시간에 맞춰 순차적으로 공개됩니다.</p>';
  });
}

function agRenderPostPage() {
  const root = document.querySelector('[data-post-detail]');
  if (!root) return;
  const slug = new URLSearchParams(location.search).get('slug');
  const post = agPostBySlug(slug);
  if (!post) {
    root.innerHTML = '<div class="page-copy"><h1>글을 찾을 수 없습니다</h1><p>주소가 올바른지 다시 확인해주세요.</p></div>';
    document.title = '글을 찾을 수 없습니다 | AG FE Guide';
    return;
  }
  if (!agPublished(post)) {
    root.innerHTML = '<div class="page-copy"><span class="meta">예약 글</span><h1>아직 공개 전인 글입니다</h1><p>이 글은 ' + agFormatDate(post.publishAt) + ' 이후 공개됩니다.</p></div>';
    document.title = '예약 글 | AG FE Guide';
    return;
  }
  const related = (post.related || []).map(agPostBySeq).filter(Boolean).filter(agPublished).slice(0, 2);
  const docLink = post.doc ? `<p class="doc-link">더 자세한 기본 문법은 <a href="${AG_DOCS[post.doc]}" target="_blank" rel="noopener">공식 문서</a>에서 확인할 수 있습니다.</p>` : '';
  const compare = post.compare ? `<section><h2>비교표</h2><table><tbody>${post.compare.map(function (row) { return '<tr>' + row.map(function (cell) { return '<td>' + agEscape(cell) + '</td>'; }).join('') + '</tr>'; }).join('')}</tbody></table></section>` : '';
  const checklist = post.checklist ? `<section><h2>마지막 체크리스트</h2><ul class="check-list">${post.checklist.map(function (item) { return '<li>' + agEscape(item) + '</li>'; }).join('')}</ul></section>` : '';
  const relatedHtml = related.length ? `<section class="related-posts"><h2>함께 보면 좋은 글</h2><ul>${related.map(function (item) { return '<li><a href="' + agPostUrl(item) + '">' + item.title + '</a></li>'; }).join('')}</ul></section>` : '';
  root.innerHTML = `<article class="article-detail">
    <span class="meta">${AG_CATEGORIES[post.category]} · ${post.type} · ${agFormatDate(post.publishAt)}</span>
    <h1>${post.title}</h1>
    <p class="lead">${post.problem}</p>
    <section><h2>먼저 이해할 점</h2><p>${post.summary}</p>${post.details.map(function (text) { return '<p>' + text + '</p>'; }).join('')}</section>
    ${compare}
    <section><h2>${post.codeTitle}</h2><pre><code>${agEscape(post.code)}</code></pre></section>
    <section><h2>초보자가 놓치기 쉬운 부분</h2><p>코드를 따라 쓸 때는 결과만 맞추기보다 왜 이 위치에 이 속성이나 함수가 들어가는지 확인하는 것이 좋습니다. 작은 예제라도 구조, 이름, 실행 순서를 함께 보면 다음 글의 개념과 연결됩니다.</p><p>특히 ${AG_CATEGORIES[post.category]} 학습에서는 한 번에 많은 문법을 외우기보다 같은 예제를 조금씩 바꿔보는 방식이 오래 남습니다. 에러가 나면 메시지를 먼저 읽고, 방금 바꾼 줄부터 되짚어보세요.</p></section>
    ${checklist}
    ${docLink}
    ${relatedHtml}
  </article>`;
  document.title = post.title + ' | AG FE Guide';
  const description = document.querySelector('meta[name="description"]');
  if (description) description.setAttribute('content', post.summary);
}

function agScheduleNextRender() {
  const future = AG_POSTS.map(function (post) { return agDate(post.publishAt); }).filter(function (date) { return date > agNow(); }).sort(function (a, b) { return a - b; })[0];
  if (!future) return;
  const delay = Math.min(future.getTime() - Date.now() + 1000, 2147483647);
  window.setTimeout(function () { agRenderLists(); agRenderPostPage(); agScheduleNextRender(); }, delay);
}

function agInitPosts() {
  agRenderLists();
  agRenderPostPage();
  agScheduleNextRender();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', agInitPosts);
} else {
  agInitPosts();
}
